### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [danbapp/prj-rev-bwfs-dasmoto#7]
https://github.com/danbapp/prj-rev-bwfs-dasmoto/blob/master/dasmotos-arts-crafts/assets/main.css#L29-L31

You have this style being repeated in multiple CSS rules. 

Write a single rule with multiple selectors to apply this style to all elements in one place.

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```
